### ISSUE TITLE
Delete Comment

### ISSUE THREAD

**Issue by jivteshsingh** [VaibhavAswal/gangLandServer#2]
Hey, I would like to add the delete comment functionality. Can u please assign me this issue. I would like to work on it.
@VaibhavAswal

**Comment by VaibhavAswal** [comment]
Sure @jivteshsingh 
If you need any help ping me here

**Comment by jivteshsingh** [comment]
Hey, I have implemented the functionality and created a pull request.
@VaibhavAswal

**Comment by VaibhavAswal** [comment]
Hey, @jivteshsingh i have reviewed your request and have merged the changes whith the main branch. 
Thanks for your valuable contribution.
