### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by jivteshsingh** [VaibhavAswal/gangLandServer#4]
Hey, I would also like to add this functionality can u please assign me this issue. I would like to work on it as it would be very good for the project.
@VaibhavAswal

**Comment by VaibhavAswal** [comment]
Yes it would be helpful!
Also let me know if you know react and want to contribute in the front end part too.
Here is the live deployed version: https://tollygram.vaibhavaswal.codes/

**Comment by jivteshsingh** [comment]
Thanks for assigning me this issue. After working on this issue, I will contribute in frontend part too as I know react.

**Comment by jivteshsingh** [comment]
Hey, I have implemented the functionality and created a pull request.
@VaibhavAswal

**Comment by VaibhavAswal** [comment]
Merged :)
