### ISSUE TITLE
Hey Vaibhav

### ISSUE THREAD

**Issue by vaibhav4gaur** [VaibhavAswal/gangLandServer#8]
Hey your backend server repository on shadow line is error so change the Shadow login and password in inner side

**Comment by VaibhavAswal** [comment]
Sorry, can you explain a bit more.

**Comment by vaibhav4gaur** [comment]
yes vaibhav , there is your backend server is Tollygram in this website , there is a error make 
![Screenshot 2022-10-19 at 4 52 06 PM](https://user-images.githubusercontent.com/110227490/196677733-4c99055f-c965-43ef-a719-02865d367eec.png)  in vaibhav gaur write  i am name so there is a more shadow behind my icon - name

**Comment by vaibhav4gaur** [comment]
Error: -  it accepted random email id and it does not follow verification email address properly with  an phone number not matching ......

**Comment by VaibhavAswal** [comment]
Verification features are not yet implemented, the the application is still in development phase so new features are added with time. 
However the shadow is designed to look like that. You can suggest youe design changes in the front-end repository i will merge them.
Thankyou

**Comment by vaibhav4gaur** [comment]
but how i can changed and where i find your front - end repository.......
